// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJlnyQRLxke2wHtDPERW_NTzcn-fY8XA8',
    appId: '1:551360748117:web:2d95a9b00f386c877952dc',
    messagingSenderId: '551360748117',
    projectId: 'whatsapp-clone-firebase-545e6',
    authDomain: 'whatsapp-clone-firebase-545e6.firebaseapp.com',
    storageBucket: 'whatsapp-clone-firebase-545e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHAC8_tK1Qu50oDZzgraYUaqPwLnTUhfU',
    appId: '1:551360748117:android:4a58b5504445444f7952dc',
    messagingSenderId: '551360748117',
    projectId: 'whatsapp-clone-firebase-545e6',
    storageBucket: 'whatsapp-clone-firebase-545e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7bTSB59Nbj8_s448byl1q3GEqoTypbK8',
    appId: '1:551360748117:ios:54fee209e427613f7952dc',
    messagingSenderId: '551360748117',
    projectId: 'whatsapp-clone-firebase-545e6',
    storageBucket: 'whatsapp-clone-firebase-545e6.appspot.com',
    iosClientId: '551360748117-gfp5disp3r18m3vlrl0tpj55bil0058d.apps.googleusercontent.com',
    iosBundleId: 'com.example.watsappClone',
  );
}
